version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-chat-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo-db:27017/chatapp
    command: >
      /app/wait-for-it.sh mongo-db:27017 -- 
      gunicorn -w 2 -b 0.0.0.0:5000 --timeout 120 app:app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
