apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-chat-app-deployment
  labels:
    app: flask-chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-chat-app
  template:
    metadata:
      labels:
        app: flask-chat-app
    spec:
      containers:
      - name: flask-chat-app
        image: alexandrefenayrou/flask-chat-app:latest  # Image depuis Docker Hub
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: app-storage
          mountPath: /app/data
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: flask-chat-app-pvc
