apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data-pv
  labels:
    app: flask-chat-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-chat-app-pvc
  labels:
    app: flask-chat-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
