apiVersion: v1
kind: Service
metadata:
  name: flask-chat-app-service
  labels:
    app: flask-chat-app
spec:
  type: NodePort
  selector:
    app: flask-chat-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
