- hosts: nodes
  become: yes
  tasks:
  - name: ensure docker is installed
    apt:
      name: docker.io
      state: latest
      update_cache: yes
      
  - name: ensure docker-compose is installed
    apt:
      name: docker-compose
      state: latest
      update_cache: yes

  - name: Added user to docker group
    user:
      name: vagrant
      groups: docker
  
  - name: Check Flask application health
    uri:
      url: http://192.168.56.51:5000/health
      method: GET
      status_code: 200
    register: health_check

  - name: Print health status
    debug:
      msg: "Health check passed!" 
    when: health_check.status == 200
