---
- name: Provision Flask Chat App VM
  hosts: app_server
  become: true

  vars:
    app_dir: /home/vagrant/app

  tasks:

    - name: Update APT packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required system packages
      apt:
        name:
          - python3
          - python3-pip
          - mongodb
          - git
        state: present

    - name: Ensure MongoDB is running
      systemd:
        name: mongodb
        state: started
        enabled: yes

    - name: Install Python dependencies for Flask app
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        executable: pip3

    - name: Start Flask Chat App
      command: python3 app.py
      args:
        chdir: "{{ app_dir }}"
      async: 1000
      poll: 0

    - name: Health Check - Ensure Flask app is running
      uri:
        url: http://localhost:5000
        status_code: 200
      register: health_check

    - name: Display health check results
      debug:
        var: health_check.status